### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by viktornord** [prashantagarwal/RunJS-Slackbot#1]
Hi, there! I would like to use this great extension but I can't due to errors while installing dependencies

**Comment by viktornord** [comment]
When I am trying to install dependencies, it installs infinitely and I get the error
npm ERR! fetch failed http://tklxp368.westernacher.com:8081/artifactory/api/npm/npm/ws/-/ws-1.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND tklxp368.westernacher.com tklxp368.westernacher.com:8081

**Comment by prashantagarwal** [comment]
Hey @viktornord are you using windows system. I was not able to reproduce this on my machine. Try updating npm and node

**Comment by viktornord** [comment]
@prashantagarwal, I am using mac and node v6.0.0, Maybe I have to try with lower version
there were addition configuration for npm, now it is ok
